// Generated by CoffeeScript 1.10.0
var CONST, fillChar;

CONST = require('../const');


/**
 * 填充字符串
 * @example 'lab'.fillChar(5, '_', CONST.LEFT) // __lab
 * @example 'lab'.fillChar(4, '_', CONST.RIGHT) // lab_
 * @example 'lab'.fillChar(6, '_') // lab___
 * @param length {number} 最小长度
 * @param char {string} 填充字符
 * @param position {number} 位置 0 左 1 右
 * @returns {string}
 */

fillChar = function(length, char, position) {
  var fillStr, len;
  len = length - this.length + 1;
  fillStr = new Array(len > 0 ? len : 0).join(char || '0');
  if (position === CONST.LEFT) {
    return fillStr + this;
  } else {
    return this + fillStr;
  }
};

if (!String.prototype.fillChar) {
  String.prototype.fillChar = fillChar;
}

if (require.main === module) {
  console.log('lab'.fillChar(5, '_', CONST.LEFT));
  console.log('lab'.fillChar(4, '_', CONST.RIGHT));
  console.log('lab'.fillChar(6, '_'));
}

//# sourceMappingURL=fillChar.js.map
