// Generated by CoffeeScript 1.10.0

/**
 * 静态变量
 * @constructor
 */
var Constants;

Constants = function() {

  /**
   * 左
   * @type {number}
   */
  this.LEFT = 0;

  /**
   * 右
   * @type {number}
   */
  this.RIGHT = 1;
};

module.exports = new Constants;

//# sourceMappingURL=const.js.map
